---
- name: Install Docker (Latest Stable)
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

#aws cli
- name: Install AWS CLI v2 
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    ./aws/install
    rm -rf aws awscliv2.zip
  args:
    creates: /usr/local/bin/aws

#kubectl
- name: Install kubectl 
  get_url:
    url: "https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0700'

#Helm
- name: Install Helm
  shell: |
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    chmod 700 get_helm.sh
    ./get_helm.sh
  args:
    creates: /usr/local/bin/helm

#Trivy 
- name: Install Trivy 
  shell: |
    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
  args:
    creates: /usr/local/bin/trivy


#Eksctl
- name: Install eksctl 
  shell: |
    curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz" | tar -xz -C /usr/local/bin
  args:
    creates: /usr/local/bin/eksctl