pipeline {
    agent any
    tools {
        jdk 'jdk17'
        nodejs 'node23'
    }
    environment {
        SCANNER_HOME=tool 'sonar-scanner'
    }
    stages {
        stage ("clean workspace") {
            steps {
                cleanWs()
            }
        }
        stage ("Git Checkout") {
            steps {
                git branch: 'main',
                    url : 'https://github.com/harshal019/food-delivery-devops-microservices.git'            
                }
        }

        stage("Sonarqube Analysis"){
            steps{
                withSonarQubeEnv('sonar-server') {
                    sh ''' 
                        $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=zomato \
                        -Dsonar.projectKey=zomato 
                    '''
                }
            }
        }
        stage("Code Quality Gate"){
           steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'Sonar-token' 
                }
            } 
        }

        stage("Install NPM Dependencies") {
            steps {
                dir("app"){
                    sh "npm install"
                }
            }
        }

        stage('OWASP FS SCAN') {
            steps {
                dependencyCheck(
                    additionalArguments: '--scan ./app --out .',
                    odcInstallation: 'DP-Check'
                )
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            }
        }


        stage ("Trivy File Scan") {
            steps {
                sh "trivy fs . > trivy.txt"
            }
        }

        stage ("Build Docker Image") {
            steps {
                sh "docker build -t zomato -f docker/Dockerfile ."
            }
        }

        stage ("Trivy Image Scan") {
            steps {
                 sh "trivy image zomato > trivy-image.txt || true"

            }
        }

        stage ("Tag & Push to DockerHub") {
            steps {
                withCredentials([usernamePassword( credentialsId: 'docker',
                    usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh """
                        echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin
                        docker tag zomato harshalg01/zomato-app:latest
                        docker push harshalg01/zomato-app:latest
                        docker logout
                    """
                }
            }
        }


         stage("Trigger CD Pipeline") {
            steps {
                build job: 'zomato-cd', wait: false
            }
        }
    }
   post {
        always {
            emailext(
                attachmentsPattern: 'trivy*.txt',
                subject: "${currentBuild.currentResult}: Job ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: """
                    <html>
                    <body>
                        <div style="background-color: #FFA07A; padding: 10px;">
                            <p>Project: ${env.JOB_NAME}</p>
                            <p>Build: ${env.BUILD_NUMBER}</p>
                            <p>Status: ${currentBuild.currentResult}</p>
                            <p>URL: ${env.BUILD_URL}</p>
                        </div>
                    </body>
                    </html>
                """,
                to: 'harshaldgharat01@gmail.com',
                mimeType: 'text/html'
            )
        }
    }

}
